spring:
  data:
    rest:
      basePath: /api
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: postgres
    password: postgres
    driver: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      dialect: PostgreSQLDialect
      ddl-auto: create-drop
logging:
  level:
    org.springframework.security: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"

management.endpoint.health.show-details: when-authorized
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation: true
spring.jpa.properties.hibernate.hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor

